listener 8883
protocol mqtt

cafile /reference-state/pki/ca.pem
certfile /reference-state/pki/server.crt
keyfile /reference-state/pki/server.key
require_certificate true
use_identity_as_username true
allow_anonymous false
acl_file /reference-state/mosquitto/acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 5

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
